export const STATUS_RELATION = {
  TBD: "Sem data definida",
  NS: "Não iniciado",
  "1H": "1º Tempo",
  HT: "Intervalo",
  "2H": "2º Tempo",
  BT: "Prorrogação",
  P: "Pênaltis",
  SUSP: "Suspenso",
  INT: "Interrompido",
  FT: "Finalizado",
  AET: "Finalizado",
  PEN: "Finalizado",
  PST: "Adiado",
  CANC: "Cancelado",
  ABD: "Jogo Suspenso",
  AWD: "Finalizado",
  WO: "Finalizado",
  LIVE: "Ao vivo",
};
