export const STATS_RELATION = {
  "Shots on Goal": "Chutes ao Gol",
  "Shots off Goal": "Chutes pra fora",
  "Total Shots": "Finalizações",
  "Blocked Shots": "Chutes bloqueados",
  "Shots insidebox": "Chutes dentro da área",
  "Shots outsidebox": "Chutes fora da área",
  Fouls: "Faltas",
  "Corner Kicks": "Escanteios",
  Offsides: "Impedimentos",
  "Ball Possession": "Posse de bola",
  "Yellow Cards": "Cartões amarelos",
  "Red Cards": "Cartões vermelhos",
  "Goalkeeper Saves": "Defesas",
  "Total passes": "Total de passes",
  "Passes accurate": "Precisão de passes",
  "Passes %": "Porcentagem de passes",
  expected_goals: "Média de gols",
} as const;
